server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://logs-prod-030.grafana.net/loki/api/v1/push
    basic_auth:
      username: "${LOKI_USERNAME}"
      password: "${LOKI_PASSWORD}"
scrape_configs:
  - job_name: logs  # 통합된 job 이름
    static_configs:
      - targets:
          - localhost
        labels:
          job: logs
          log_level: info  # info 레벨 라벨 추가
          __path__: /var/log/info/*.log
      - targets:
          - localhost
        labels:
          job: logs
          log_level: warn  # warn 레벨 라벨 추가
          __path__: /var/log/warn/*.log
      - targets:
          - localhost
        labels:
          job: logs
          log_level: error  # error 레벨 라벨 추가
          __path__: /var/log/error/*.log
    pipeline_stages:
      # traceId 추출 (모든 로그에서 추출 가능)
      - regex:
          expression: '\\[traceId=(?P<traceId>[^\\]]+)\\]'
      # HTTP Request 관련 라벨 추출 (HTTP Request 메시지에서만 추출)
      - regex:
          expression: 'HTTPMethod=(?P<HTTPMethod>[A-Z]+) Path=(?P<Path>\S+) from IP=(?P<IP>[0-9a-fA-F:]+)'
      # HTTP Response 관련 라벨 추출 (HTTP Response 메시지에서만 추출)
      - regex:
          expression: 'ResponseCode=(?P<ResponseCode>\\d+) ResponseMessage="(?P<ResponseMessage>[^"]+)"'
      # ExecutionTime 추출 (ExecutionTime이 있는 메시지에서만 추출)
      - regex:
          expression: 'ExecutionTime=(?P<ExecutionTime>\\d+ms)'
      - labels:
          traceId: traceId
          HTTPMethod: HTTPMethod
          Path: Path
          IP: IP
          ResponseCode: ResponseCode
          ResponseMessage: ResponseMessage
          ResponseData: ResponseData
          ExecutionTime: ExecutionTime
